// <auto-generated />
using ArbitrageTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArbitrageTracker.Data.Migrations
{
    [DbContext(typeof(ArbitrageDbContext))]
    partial class ArbitrageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ArbitrageTracker.Data.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("ArbitrageTracker.Data.Entities.BucketSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AvgHighPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AvgLowPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HighPriceVolume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LowPriceVolume")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "Interval", "Timestamp")
                        .IsUnique();

                    b.ToTable("BucketSnapshots");
                });

            modelBuilder.Entity("ArbitrageTracker.Data.Entities.ItemMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Examine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HighAlch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LowAlch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Members")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItemMappings");
                });

            modelBuilder.Entity("ArbitrageTracker.Data.Entities.OpportunitySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BuyPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DetectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpectedCycleProfit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetMargin")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProxyEvaluatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ProxyValidated")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SafetyScore")
                        .HasColumnType("REAL");

                    b.Property<long>("SellPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "DetectedAt");

                    b.ToTable("OpportunitySnapshots");
                });

            modelBuilder.Entity("ArbitrageTracker.Data.Entities.PriceSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CapturedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("High")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HighTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Low")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LowTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "CapturedAt");

                    b.ToTable("PriceSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
